import { SupportedLanguage, LanguageInfo } from '../types';

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  // Global
  { code: 'en', name: 'English', nativeName: 'English (US/Global)', flag: '🌐', isNational: false },
  // National (India)
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', isNational: true },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳', isNational: true },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', isNational: true },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', isNational: true },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', isNational: true },
  // International
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', isNational: false },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', isNational: false },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', isNational: false },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', isNational: false },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳', isNational: false },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', isNational: false },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', isNational: false },
];

export const UI_TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    liveNews: 'Live News',
    fiveMinBrief: '5-Min Brief',
    forYou: 'For You',
    digests: 'Digests',
    engineSeo: 'Engine & SEO',
    flashWire: 'FLASH TECH WIRE',
    nextBatchIn: 'Next batch in:',
    pause: 'Pause',
    resume: 'Resume',
    searchPlaceholder: 'Search AI, Tech, SEO dispatches...',
    upgrade: 'Upgrade Pro',
    subscribe: 'Email Subscription',
    subscribeNewsletter: 'Subscribe to 5-Min Tech & SEO Intelligence',
    newsletterDesc: 'Get curated 5-minute summaries on AI breakthroughs, Google SEO algorithm shifts, and global tech developments delivered to your inbox.',
    dailyDigest: 'Daily Morning AI & SEO Digest (8:00 AM)',
    realtimeAlerts: 'Instant 5-Minute Flash Alerts',
    weeklyWrap: 'Weekly Deep-Dive Tech Wrap (Sunday)',
    enterEmail: 'Enter your work email address...',
    subscribeNow: 'Subscribe Instantly',
    chatBotTitle: '5MIN Tech AI Copilot',
    chatBotSubtitle: 'Ask anything about AI, SEO, Tech Dispatches & India/Global News',
    askQuestion: 'Ask AI Copilot about breaking tech, SEO changes, or AI models...',
    askAiContext: 'Deep AI Context',
    readSource: 'Read Source',
    refLinks: 'Ref Links:',
    allChannels: 'ALL LIVE CHANNELS',
    storiesCount: 'stories',
    refreshedWires: 'Refreshed dynamically from 42 verified wires',
    whatChanged: 'WHAT CHANGED IN THE LAST 5 MINUTES',
    whyItMatters: 'WHY IT MATTERS',
    corroboratingSources: 'CORROBORATING SOURCES & FACT-CHECK',
    audioBrief: 'Audio Brief',
  },
  hi: {
    liveNews: 'लाइव टेक न्यूज़',
    fiveMinBrief: '5-मिनट ब्रीफ',
    forYou: 'आपके लिए',
    digests: 'डाइजेस्ट',
    engineSeo: 'इंजन व SEO',
    flashWire: 'फ्लैश रनिंग न्यूज़',
    nextBatchIn: 'अगला बैच:',
    pause: 'रोकें',
    resume: 'शुरू करें',
    searchPlaceholder: 'AI, टेक, SEO समाचार खोजें...',
    upgrade: 'अपग्रेड प्रो',
    subscribe: 'ईमेल सदस्यता',
    subscribeNewsletter: '5-मिनट टेक व SEO इंटेलिजेंस की सदस्यता लें',
    newsletterDesc: 'AI सफलताओं, Google SEO एल्गोरिद्म बदलावों और वैश्विक टेक विकास पर 5-मिनट के सारांश अपने इनबॉक्स में पाएं।',
    dailyDigest: 'दैनिक सुबह AI और SEO डाइजेस्ट (सुबह 8:00 बजे)',
    realtimeAlerts: 'तत्काल 5-मिनट फ्लैश अलर्ट',
    weeklyWrap: 'साप्ताहिक डीप-डाइव टेक रैप (रविवार)',
    enterEmail: 'अपना ईमेल दर्ज करें...',
    subscribeNow: 'तुरंत सब्सक्राइब करें',
    chatBotTitle: '5MIN टेक AI कोपायलट',
    chatBotSubtitle: 'AI, SEO, टेक समाचार और भारत/वैश्विक समाचार पर कुछ भी पूछें',
    askQuestion: 'ताजा तकनीक, SEO बदलाव या AI मॉडल के बारे में पूछें...',
    askAiContext: 'गहन AI विश्लेषण',
    readSource: 'स्रोत पढ़ें',
    refLinks: 'संदर्भ लिंक:',
    allChannels: 'सभी लाइव चैनल',
    storiesCount: 'कहानियां',
    refreshedWires: '42 सत्यापित स्रोतों से ताज़ा अपडेट',
    whatChanged: 'पिछले 5 मिनट में क्या बदला',
    whyItMatters: 'यह क्यों महत्वपूर्ण है',
    corroboratingSources: 'सत्यापित स्रोत और तथ्य जांच',
    audioBrief: 'ऑडियो ब्रीफ',
  },
  bn: {
    liveNews: 'লাইভ টেক সংবাদ',
    fiveMinBrief: '৫-মিনিট ব্রিফ',
    forYou: 'আপনার জন্য',
    digests: 'ডাইজেস্ট',
    engineSeo: 'ইঞ্জিন ও এসইও',
    flashWire: 'ফ্ল্যাশ রানিং নিউজ',
    nextBatchIn: 'পরবর্তী ব্যাচ:',
    pause: 'থামান',
    resume: 'চালান',
    searchPlaceholder: 'এআই, টেক ও এসইও খুঁজুন...',
    upgrade: 'আপগ্রেড প্রো',
    subscribe: 'ইমেল সাবস্ক্রিপশন',
    subscribeNewsletter: '৫-মিনিট টেক ও এসইও সাবস্ক্রাইব করুন',
    newsletterDesc: 'এআই এবং এসইও অ্যালগরিদম আপডেটের ৫-মিনিটের সারাংশ ইমেলে পান।',
    dailyDigest: 'দৈনিক সকালের ব্রিফ (৮:০০ AM)',
    realtimeAlerts: 'তাৎক্ষণিক ৫-মিনিট ফ্ল্যাশ অ্যালার্ট',
    weeklyWrap: 'সাপ্তাহিক টেক পর্যালোচনা',
    enterEmail: 'আপনার ইমেল লিখুন...',
    subscribeNow: 'সাবস্ক্রাইব করুন',
    chatBotTitle: '৫-মিনিট এআই কোপাইলট',
    chatBotSubtitle: 'এআই ও প্রযুক্তি সম্পর্কে যেকোনো প্রশ্ন করুন',
    askQuestion: 'প্রযুক্তি এবং এসইও সম্পর্কে জিজ্ঞাসা করুন...',
    askAiContext: 'এআই বিশ্লেষণ',
    readSource: 'উৎস পড়ুন',
    refLinks: 'উৎস লিঙ্ক:',
    allChannels: 'সকল লাইভ চ্যানেল',
    storiesCount: 'সংবাদ',
    refreshedWires: 'যাচাইকৃত উৎস থেকে আপডেট',
    whatChanged: 'গত ৫ মিনিটে যা বদলেছে',
    whyItMatters: 'কেন এটি গুরুত্বপূর্ণ',
    corroboratingSources: 'যাচাইকৃত সূত্রসমূহ',
    audioBrief: 'অডিও ব্রিফ',
  },
  ta: {
    liveNews: 'நேரலை டெக் செய்திகள்',
    fiveMinBrief: '5-நிமிட சுருக்கம்',
    forYou: 'உங்களுக்காக',
    digests: 'செய்தி தொகுப்பு',
    engineSeo: 'இயந்திரம் & எஸ்சிஓ',
    flashWire: 'மின்னல் நேரலை செய்திகள்',
    nextBatchIn: 'அடுத்த தொகுப்பு:',
    pause: 'நிறுத்து',
    resume: 'தொடங்கு',
    searchPlaceholder: 'AI, டெக், எஸ்சிஓ தேடுக...',
    upgrade: 'ப்ரோ மேம்படுத்தல்',
    subscribe: 'மின்னஞ்சல் சந்தா',
    subscribeNewsletter: '5-நிமிட டெக் & எஸ்சிஓ சந்தா பெறுக',
    newsletterDesc: 'AI மற்றும் எஸ்சிஓ மாற்றங்களின் 5 நிமிட சுருக்கங்களை உங்கள் மின்னஞ்சலில் பெறுங்கள்.',
    dailyDigest: 'தினசரி காலை அறிக்கை (8:00 AM)',
    realtimeAlerts: 'உடனடி 5-நிமிட விழிப்பூட்டல்',
    weeklyWrap: 'வாராந்திர டெக் அலசல்',
    enterEmail: 'மின்னஞ்சலை உள்ளிடுக...',
    subscribeNow: 'இப்போதே சந்தா பெறுக',
    chatBotTitle: 'AI டெக் உதவியாளர்',
    chatBotSubtitle: 'AI, எஸ்சிஓ & உலகளாவிய செய்திகளை கேட்கவும்',
    askQuestion: 'தொழில்நுட்பம் பற்றி கேளுங்கள்...',
    askAiContext: 'AI பகுப்பாய்வு',
    readSource: 'மூலத்தை படிக்க',
    refLinks: 'குறிப்பு இணைப்புகள்:',
    allChannels: 'அனைத்து சேனல்கள்',
    storiesCount: 'செய்திகள்',
    refreshedWires: 'உறுதிப்படுத்தப்பட்ட செய்திகள்',
    whatChanged: 'கடந்த 5 நிமிடங்களில் என்ன மாறியது',
    whyItMatters: 'ஏன் முக்கியமானது',
    corroboratingSources: 'சரிபார்க்கப்பட்ட ஆதாரங்கள்',
    audioBrief: 'ஆடியோ அறிக்கை',
  },
  te: {
    liveNews: 'లైవ్ టెక్ వార్తలు',
    fiveMinBrief: '5-నిమిషాల బ్రీఫ్',
    forYou: 'మీ కోసం',
    digests: 'డైజెస్ట్',
    engineSeo: 'ఇంజన్ & ఎస్ఈఓ',
    flashWire: 'ఫ్లాష్ రన్నింగ్ న్యూస్',
    nextBatchIn: 'తదుపరి అప్‌డేట్:',
    pause: 'పాజ్',
    resume: 'ప్లే',
    searchPlaceholder: 'AI, టెక్నాలజీ, ఎస్ఈఓ శోధించండి...',
    upgrade: 'ప్రోకి అప్‌గ్రేడ్',
    subscribe: 'ఈమెయిల్ సబ్‌స్క్రిప్షన్',
    subscribeNewsletter: '5-నిమిషాల టెక్ & ఎస్ఈఓ వార్తలకు సబ్‌స్క్రైబ్ చేయండి',
    newsletterDesc: 'AI మరియు గూగుల్ ఎస్ఈఓ అల్గారిథమ్ మార్పుల 5-నిమిషాల సారాంశాలను ఈమెయిల్‌లో పొందండి.',
    dailyDigest: 'రోజువారీ ఉదయం బులెటిన్ (8:00 AM)',
    realtimeAlerts: 'తక్షణ 5-నిమిషాల అలర్ట్స్',
    weeklyWrap: 'వారాంతపు టెక్ రివ్యూ',
    enterEmail: 'మీ ఈమెయిల్ నమోదు చేయండి...',
    subscribeNow: 'సబ్‌స్క్రైబ్ చేయండి',
    chatBotTitle: 'AI టెక్ కోపైలట్',
    chatBotSubtitle: 'AI, ఎస్ఈఓ మరియు టెక్నాలజీ గురించి అడగండి',
    askQuestion: 'టెక్నాలజీ ప్రశ్న అడగండి...',
    askAiContext: 'AI విశ్లేషణ',
    readSource: 'సోర్స్ చదవండి',
    refLinks: 'సోర్స్ లింక్స్:',
    allChannels: 'అన్ని లైవ్ ఛానెల్స్',
    storiesCount: 'కథనాలు',
    refreshedWires: 'ధృవీకరించబడిన సోర్సెస్',
    whatChanged: 'గత 5 నిమిషాల్లో ఏం మారింది',
    whyItMatters: 'ఎందుకు ముఖ్యం',
    corroboratingSources: 'నిర్ధారించబడిన మూలాలు',
    audioBrief: 'ఆడియో బ్రీఫ్',
  },
  mr: {
    liveNews: 'लाइव्ह टेक बातम्या',
    fiveMinBrief: '५-मिनिट ब्रीफ',
    forYou: 'तुमच्यासाठी',
    digests: 'डायजेस्ट',
    engineSeo: 'इंजिन व एसईओ',
    flashWire: 'फ्लॅश धावत्या बातम्या',
    nextBatchIn: 'पुढील तुकडी:',
    pause: 'थांबवा',
    resume: 'सुरू करा',
    searchPlaceholder: 'AI, तंत्रज्ञान, SEO शोधा...',
    upgrade: 'अपग्रेड प्रो',
    subscribe: 'ईमेल सदस्यता',
    subscribeNewsletter: '५-मिनिट टेक व SEO इंटेलिजन्स मिळवा',
    newsletterDesc: 'AI आणि गुगल SEO बदलांचे ५ मिनिटांचे सारांश थेट इनबॉक्समध्ये मिळवा.',
    dailyDigest: 'दैनिक सकाळचा ब्रीफ (८:०० AM)',
    realtimeAlerts: 'झटपट ५-मिनिट फ्लॅश अलर्ट',
    weeklyWrap: 'साप्ताहिक तंत्रज्ञान आढावा',
    enterEmail: 'तुमचा ईमेल टाका...',
    subscribeNow: 'सबस्क्राइब करा',
    chatBotTitle: '५-मिनिट टेक AI बॉट',
    chatBotSubtitle: 'AI आणि तंत्रज्ञानाबद्दल काहीही विचारा',
    askQuestion: 'तंत्रज्ञानाबद्दल प्रश्न विचारा...',
    askAiContext: 'सखोल AI विश्लेषण',
    readSource: 'मूळ स्रोत वाचा',
    refLinks: 'संदर्भ लिंक्स:',
    allChannels: 'सर्व लाइव्ह वाहिन्या',
    storiesCount: 'बातम्या',
    refreshedWires: 'सत्यापित स्त्रोतांकडून ताजेतवाने',
    whatChanged: 'गेल्या ५ मिनिटांत काय बदलले',
    whyItMatters: 'हे का महत्त्वाचे आहे',
    corroboratingSources: 'तपासलेले पुरावे आणि स्रोत',
    audioBrief: 'ऑडिओ ब्रीफ',
  },
  es: {
    liveNews: 'Noticias en Vivo',
    fiveMinBrief: 'Resumen de 5 Min',
    forYou: 'Para Ti',
    digests: 'Boletines',
    engineSeo: 'Motor y SEO',
    flashWire: 'NOTICIAS FLASH TECH',
    nextBatchIn: 'Próxima actualización en:',
    pause: 'Pausar',
    resume: 'Reanudar',
    searchPlaceholder: 'Buscar noticias de IA, Tecnología, SEO...',
    upgrade: 'Mejorar a Pro',
    subscribe: 'Suscripción por Correo',
    subscribeNewsletter: 'Suscríbete a Inteligencia Tech y SEO de 5 Minutos',
    newsletterDesc: 'Recibe resúmenes de 5 minutos sobre avances en IA, cambios en algoritmos de Google SEO y tecnología global.',
    dailyDigest: 'Resumen Matutino de IA y SEO (8:00 AM)',
    realtimeAlerts: 'Alertas Flash Instantáneas cada 5 Minutos',
    weeklyWrap: 'Resumen Tecnológico Semanal (Domingos)',
    enterEmail: 'Ingresa tu correo corporativo...',
    subscribeNow: 'Suscribirse Ahora',
    chatBotTitle: 'Copiloto de IA Tecnológica 5MIN',
    chatBotSubtitle: 'Pregunta lo que sea sobre IA, SEO, Hardware y Noticias Globales',
    askQuestion: 'Pregunta al Copiloto sobre IA o SEO...',
    askAiContext: 'Contexto Profundo de IA',
    readSource: 'Leer Fuente',
    refLinks: 'Enlaces de Ref:',
    allChannels: 'TODOS LOS CANALES',
    storiesCount: 'noticias',
    refreshedWires: 'Actualizado desde 42 agencias verificadas',
    whatChanged: 'QUÉ CAMBIÓ EN LOS ÚLTIMOS 5 MINUTOS',
    whyItMatters: 'POR QUÉ IMPORTA',
    corroboratingSources: 'FUENTES Y VERIFICACIÓN DE HECHOS',
    audioBrief: 'Audio Resumen',
  },
  fr: {
    liveNews: 'En Direct',
    fiveMinBrief: 'Flash 5-Min',
    forYou: 'Pour Vous',
    digests: 'Digests',
    engineSeo: 'Moteur & SEO',
    flashWire: 'DÉPÊCHES FLASH TECH',
    nextBatchIn: 'Prochaine mise à jour dans :',
    pause: 'Pause',
    resume: 'Reprendre',
    searchPlaceholder: 'Rechercher IA, Tech, SEO...',
    upgrade: 'Passer Pro',
    subscribe: 'Abonnement Email',
    subscribeNewsletter: 'Abonnez-vous à l’Intelligence Tech & SEO en 5 Min',
    newsletterDesc: 'Recevez les synthèses en 5 minutes sur l’IA, les algorithmes SEO Google et l’écosystème tech mondial.',
    dailyDigest: 'Digest Matinal IA & SEO (08h00)',
    realtimeAlerts: 'Alertes Flash Instantanées 5-Min',
    weeklyWrap: 'Bilan Hebdomadaire Tech (Dimanche)',
    enterEmail: 'Entrez votre adresse email pro...',
    subscribeNow: 'S’abonner Immédiatement',
    chatBotTitle: 'Copilote IA Tech 5MIN',
    chatBotSubtitle: 'Posez vos questions sur l’IA, le SEO et la Tech Mondiale',
    askQuestion: 'Interrogez l’assistant IA sur la tech...',
    askAiContext: 'Contexte IA Approfondi',
    readSource: 'Lire la Source',
    refLinks: 'Liens de Réf :',
    allChannels: 'TOUS LES CANAUX',
    storiesCount: 'articles',
    refreshedWires: 'Actualisé depuis 42 agences vérifiées',
    whatChanged: 'CE QUI A CHANGÉ CES 5 DERNIÈRES MINUTES',
    whyItMatters: 'POURQUOI C’EST CRUCIAL',
    corroboratingSources: 'SOURCES ET VÉRIFICATION CROISÉE',
    audioBrief: 'Flash Audio',
  },
  de: {
    liveNews: 'Live-Nachrichten',
    fiveMinBrief: '5-Minuten-Brief',
    forYou: 'Für Dich',
    digests: 'Digests',
    engineSeo: 'Engine & SEO',
    flashWire: 'EILMELDUNGEN TECH',
    nextBatchIn: 'Nächster Abruf in:',
    pause: 'Pause',
    resume: 'Fortsetzen',
    searchPlaceholder: 'KI, Tech, SEO durchsuchen...',
    upgrade: 'Auf Pro upgraden',
    subscribe: 'E-Mail-Abonnement',
    subscribeNewsletter: '5-Minuten Tech & SEO Intelligence abonnieren',
    newsletterDesc: 'Erhalten Sie 5-minütige Zusammenfassungen zu KI-Durchbrüchen und Google SEO-Algorithmen direkt in Ihr Postfach.',
    dailyDigest: 'Täglicher Morgen-Digest (08:00 Uhr)',
    realtimeAlerts: 'Sofortige 5-Minuten-Eilmeldungen',
    weeklyWrap: 'Wöchentlicher Tech-Rückblick (Sonntag)',
    enterEmail: 'Geben Sie Ihre E-Mail-Adresse ein...',
    subscribeNow: 'Jetzt abonnieren',
    chatBotTitle: '5MIN Tech KI-Copilot',
    chatBotSubtitle: 'Fragen Sie alles zu KI, SEO, Halbleitern und globalen News',
    askQuestion: 'Stellen Sie eine Frage zu KI oder SEO...',
    askAiContext: 'Tiefer KI-Kontext',
    readSource: 'Quelle lesen',
    refLinks: 'Quellen-Links:',
    allChannels: 'ALLE LIVE-KANÄLE',
    storiesCount: 'Meldungen',
    refreshedWires: 'Dynamisch aktualisiert aus 42 verifizierten Quellen',
    whatChanged: 'WAS SICH IN DEN LETZTEN 5 MINUTEN GEÄNDERT HAT',
    whyItMatters: 'WARUM ES WICHTIG IST',
    corroboratingSources: 'QUELLENVERIFIKATION',
    audioBrief: 'Audio-Briefing',
  },
  ja: {
    liveNews: 'ライブ速報',
    fiveMinBrief: '5分ダイジェスト',
    forYou: 'おすすめ',
    digests: 'ニュースレター',
    engineSeo: 'エンジン & SEO',
    flashWire: '速報テクノロジーフラッシュ',
    nextBatchIn: '次回更新まで:',
    pause: '一時停止',
    resume: '再開',
    searchPlaceholder: 'AI、テック、SEOニュースを検索...',
    upgrade: 'Proにアップグレード',
    subscribe: 'メール配信登録',
    subscribeNewsletter: '5分で読めるTech & SEOインテリジェンスを購読',
    newsletterDesc: '最新のAI技術革新、Google SEOアルゴリズム更新、世界各国のテック速報を毎朝5分で配信。',
    dailyDigest: '毎朝のAI & SEOダイジェスト (午前8:00)',
    realtimeAlerts: 'リアルタイム5分フラッシュ速報',
    weeklyWrap: '週間テック振り返り (日曜日)',
    enterEmail: 'メールアドレスを入力...',
    subscribeNow: '今すぐ無料購読',
    chatBotTitle: '5MIN テック AI コパイロット',
    chatBotSubtitle: '最新AI、SEO、半導体、国際テックについて質問できます',
    askQuestion: 'AIやSEOについて質問する...',
    askAiContext: '詳細AI分析',
    readSource: '一次ソースを読む',
    refLinks: '参照リンク:',
    allChannels: 'すべてのチャンネル',
    storiesCount: '件の速報',
    refreshedWires: '42の検証済み通信社から自動配信',
    whatChanged: '直近5分間の主な変更点',
    whyItMatters: 'なぜ重要なのか',
    corroboratingSources: 'クロスリファレンスと検証ソース',
    audioBrief: '音声ブリーフィング',
  },
  zh: {
    liveNews: '实时科技快讯',
    fiveMinBrief: '5分钟简报',
    forYou: '为您推荐',
    digests: '精选简报',
    engineSeo: '引擎与SEO',
    flashWire: '快讯跑马灯',
    nextBatchIn: '下次更新倒计时:',
    pause: '暂停',
    resume: '恢复',
    searchPlaceholder: '搜索AI、科技、SEO重大事件...',
    upgrade: '升级至Pro',
    subscribe: '邮件订阅',
    subscribeNewsletter: '订阅5分钟科技与SEO智能资讯',
    newsletterDesc: '精准掌握前沿AI突破、谷歌SEO搜索算法调整和全球半导体科技动态。',
    dailyDigest: '每日早间AI与SEO简报 (上午8:00)',
    realtimeAlerts: '即时5分钟闪电预警',
    weeklyWrap: '每周深度科技综述 (周日)',
    enterEmail: '输入您的工作邮箱...',
    subscribeNow: '立即免费订阅',
    chatBotTitle: '5MIN 科技AI助手',
    chatBotSubtitle: '随时咨询前沿AI、SEO排名、芯片硬件与国内外科技动态',
    askQuestion: '询问最新AI大模型或SEO更新...',
    askAiContext: 'AI深度分析',
    readSource: '阅读原始出处',
    refLinks: '参考链接:',
    allChannels: '所有实时频道',
    storiesCount: '条快讯',
    refreshedWires: '来自42家全球权威通讯社实时核实',
    whatChanged: '过去5分钟内的关键变化',
    whyItMatters: '为什么至关重要',
    corroboratingSources: '多方交叉核实验证',
    audioBrief: '语音简报',
  },
  ar: {
    liveNews: 'أخبار التكنولوجيا المباشرة',
    fiveMinBrief: 'موجز الـ 5 دقائق',
    forYou: 'مخصص لك',
    digests: 'النشرات الإخبارية',
    engineSeo: 'المحرك وتحسين محركات البحث',
    flashWire: 'أخبار عاجلة متدفقة',
    nextBatchIn: 'التحديث القادم خلال:',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    searchPlaceholder: 'ابحث في أخبار الذكاء الاصطناعي وSEO...',
    upgrade: 'الترقية إلى برو',
    subscribe: 'الاشتراك البريدي',
    subscribeNewsletter: 'اشترك في تقارير التكنولوجيا وSEO في 5 دقائق',
    newsletterDesc: 'احصل على ملخصات في 5 دقائق حول اختراقات الذكاء الاصطناعي وتحديثات خوارزميات جوجل.',
    dailyDigest: 'الموجز الصباحي اليومي (8:00 صباحاً)',
    realtimeAlerts: 'تنبيهات فورية كل 5 دقائق',
    weeklyWrap: 'الحصاد الأسبوعي للتكنولوجيا (الأحد)',
    enterEmail: 'أدخل بريدك الإلكتروني...',
    subscribeNow: 'اشترك الآن',
    chatBotTitle: 'مساعد الذكاء الاصطناعي 5MIN',
    chatBotSubtitle: 'اسأل عن الذكاء الاصطناعي وSEO وأحدث الأخبار التكنولوجية',
    askQuestion: 'اسأل المساعد الذكي عن الأخبار...',
    askAiContext: 'تحليل الذكاء الاصطناعي',
    readSource: 'قراءة المصدر',
    refLinks: 'روابط المصادر:',
    allChannels: 'جميع القنوات المباشرة',
    storiesCount: 'أخبار',
    refreshedWires: 'محدثة مباشرة من 42 وكالة إخبارية موثوقة',
    whatChanged: 'ما الذي تغير في الـ 5 دقائق الماضية',
    whyItMatters: 'أهمية هذا الحدث',
    corroboratingSources: 'المصادر المؤكدة والتحقق',
    audioBrief: 'الموجز الصوتي',
  },
  ru: {
    liveNews: 'Лента новостей',
    fiveMinBrief: '5-минутный дайджест',
    forYou: 'Для вас',
    digests: 'Дайджесты',
    engineSeo: 'Движок и SEO',
    flashWire: 'ГОРЯЧАЯ ЛЕНТА ТЕХНОЛОГИЙ',
    nextBatchIn: 'Следующее обновление через:',
    pause: 'Пауза',
    resume: 'Продолжить',
    searchPlaceholder: 'Поиск новостей ИИ, технологий, SEO...',
    upgrade: 'Перейти на Pro',
    subscribe: 'Подписка по Email',
    subscribeNewsletter: 'Подпишитесь на 5-минутный дайджест технологий и SEO',
    newsletterDesc: 'Получайте краткие сводки о прорывах в ИИ, обновлениях алгоритмов Google SEO и мировых технологиях прямо на почту.',
    dailyDigest: 'Ежедневный утренний обзор ИИ и SEO (08:00)',
    realtimeAlerts: 'Мгновенные 5-минутные флеш-оповещения',
    weeklyWrap: 'Еженедельный глубокий обзор технологий (Воскресенье)',
    enterEmail: 'Введите рабочий email...',
    subscribeNow: 'Подписаться сейчас',
    chatBotTitle: 'ИИ-ассистент 5MIN Tech',
    chatBotSubtitle: 'Спросите о последних моделях ИИ, SEO и глобальных новостях',
    askQuestion: 'Задать вопрос об ИИ или SEO...',
    askAiContext: 'Глубокий ИИ-контекст',
    readSource: 'Читать источник',
    refLinks: 'Ссылки на источники:',
    allChannels: 'ВСЕ КАНАЛЫ',
    storiesCount: 'новостей',
    refreshedWires: 'Обновлено из 42 проверенных источников',
    whatChanged: 'ЧТО ИЗМЕНИЛОСЬ ЗА ПОСЛЕДНИЕ 5 МИНУТ',
    whyItMatters: 'ПОЧЕМУ ЭТО ВАЖНО',
    corroboratingSources: 'ПРОВЕРЕННЫЕ ИСТОЧНИКИ',
    audioBrief: 'Аудио-брифинг',
  },
};

export const CATEGORY_TRANSLATIONS: Record<string, Record<SupportedLanguage, string>> = {
  All: {
    en: 'All',
    hi: 'सभी',
    bn: 'সব',
    ta: 'அனைத்தும்',
    te: 'అన్నీ',
    mr: 'सर्व',
    es: 'Todos',
    fr: 'Tout',
    de: 'Alle',
    ja: 'すべて',
    zh: '全部',
    ar: 'الكل',
    ru: 'Все',
  },
  AI: {
    en: 'AI & LLMs',
    hi: 'AI व LLM',
    bn: 'এআই ও এলএলএম',
    ta: 'AI & LLM',
    te: 'AI & LLMs',
    mr: 'AI व LLM',
    es: 'IA y LLMs',
    fr: 'IA & LLMs',
    de: 'KI & LLMs',
    ja: 'AI・大規模言語モデル',
    zh: 'AI与大语言模型',
    ar: 'الذكاء الاصطناعي',
    ru: 'ИИ и LLM',
  },
  Technology: {
    en: 'Technology',
    hi: 'तकनीक',
    bn: 'প্রযুক্তি',
    ta: 'தொழில்நுட்பம்',
    te: 'సాంకేతికత',
    mr: 'तंत्रज्ञान',
    es: 'Tecnología',
    fr: 'Technologie',
    de: 'Technologie',
    ja: 'テクノロジー',
    zh: '前沿科技',
    ar: 'التكنولوجيا',
    ru: 'Технологии',
  },
  SEO: {
    en: 'SEO & Search',
    hi: 'SEO व सर्च',
    bn: 'এসইও ও অনুসন্ধান',
    ta: 'எஸ்சிஓ & தேடல்',
    te: 'ఎస్ఈఓ & శోధన',
    mr: 'SEO व शोध',
    es: 'SEO y Búsqueda',
    fr: 'SEO & Recherche',
    de: 'SEO & Suche',
    ja: 'SEO・検索アルゴリズム',
    zh: 'SEO与搜索算法',
    ar: 'تحسين محركات البحث',
    ru: 'SEO и Поиск',
  },
  Cybersecurity: {
    en: 'Cybersecurity',
    hi: 'साइबर सुरक्षा',
    bn: 'সাইবার নিরাপত্তা',
    ta: 'சைபர் பாதுகாப்பு',
    te: 'సైబర్ సెక్యూరిటీ',
    mr: 'सायबर सुरक्षा',
    es: 'Ciberseguridad',
    fr: 'Cybersécurité',
    de: 'Cybersicherheit',
    ja: 'サイバーセキュリティ',
    zh: '网络安全',
    ar: 'الأمن السيبراني',
    ru: 'Кибербезопасность',
  },
  Startups: {
    en: 'Startups & VC',
    hi: 'स्टार्टअप व VC',
    bn: 'স্টার্টআপ ও ভিসি',
    ta: 'ஸ்டார்ட்அப் & VC',
    te: 'స్టార్టప్‌లు & VC',
    mr: 'स्टार्टअप व VC',
    es: 'Startups y Capital',
    fr: 'Startups & VC',
    de: 'Startups & VC',
    ja: 'スタートアップ・VC',
    zh: '初创与风投',
    ar: 'الشركات الناشئة',
    ru: 'Стартапы и венчур',
  },
  'India Tech': {
    en: 'India Tech (National)',
    hi: 'भारत टेक (राष्ट्रीय)',
    bn: 'ভারত টেক (জাতীয়)',
    ta: 'இந்திய தொழில்நுட்பம் (தேசிய)',
    te: 'భారత టెక్నాలజీ (జాతీయ)',
    mr: 'भारत तंत्रज्ञान (राष्ट्रीय)',
    es: 'Tech de India (Nacional)',
    fr: 'Tech Inde (Nationale)',
    de: 'Indien Tech (National)',
    ja: 'インドテック (国内速報)',
    zh: '印度科技 (国家焦点)',
    ar: 'تكنولوجيا الهند (وطني)',
    ru: 'Индия Tech (Национальные)',
  },
  'Global Tech': {
    en: 'Global Tech (International)',
    hi: 'ग्लोबल टेक (अंतरराष्ट्रीय)',
    bn: 'গ্লোবাল টেক (আন্তর্জাতিক)',
    ta: 'உலகளாவிய தொழில்நுட்பம்',
    te: 'గ్లోబల్ టెక్ (అంతర్జాతీయ)',
    mr: 'ग्लोबल टेक (आंतरराष्ट्रीय)',
    es: 'Tech Global (Internacional)',
    fr: 'Tech Mondiale (International)',
    de: 'Global Tech (International)',
    ja: 'グローバルテック (国際速報)',
    zh: '全球科技 (国际前沿)',
    ar: 'التكنولوجيا العالمية (دولي)',
    ru: 'Глобальные технологии',
  },
  DevTools: {
    en: 'DevTools & Cloud',
    hi: 'डेव टूल्स व क्लाउड',
    bn: 'ডেভ টুলস ও ক্লাউড',
    ta: 'டெவ் டூல்ஸ் & கிளவுட்',
    te: 'డెవ్ టూల్స్ & క్లౌడ్',
    mr: 'डेव्ह टूल्स व क्लाउड',
    es: 'DevTools y Cloud',
    fr: 'DevTools & Cloud',
    de: 'DevTools & Cloud',
    ja: '開発ツール・クラウド',
    zh: '开发者工具与云计算',
    ar: 'أدوات المطورين والسحابة',
    ru: 'DevTools и Облако',
  },
  Markets: {
    en: 'Tech Markets',
    hi: 'टेक मार्केट्स',
    bn: 'টেক বাজার',
    ta: 'டெக் சந்தைகள்',
    te: 'టెక్ మార్కెట్లు',
    mr: 'टेक मार्केट्स',
    es: 'Mercados Tech',
    fr: 'Marchés Tech',
    de: 'Tech-Märkte',
    ja: 'テック市場',
    zh: '科技市场',
    ar: 'أسواق التكنولوجيا',
    ru: 'Рынки технологий',
  },
};

export function t(key: string, lang: SupportedLanguage = 'en'): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS['en'][key] || key;
}

export function translateCategory(cat: string, lang: SupportedLanguage = 'en'): string {
  return CATEGORY_TRANSLATIONS[cat]?.[lang] || cat;
}
